var economy = [
    {
        "type": "farmer",
        "class": "shop",
        "sale": ["Money",],
        "buy": "Carrot",
        "sale_count": ["3"],
        "buy_count": "16",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Bread",
        "sale_count": ["4"],
        "buy_count": "16",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Rabbit",
        "sale_count": ["3"],
        "buy_count": "16",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Mutton",
        "sale_count": ["1"],
        "buy_count": "16",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Chicken",
        "sale_count": ["1"],
        "buy_count": "16",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Cake",
        "sale_count": ["2"],
        "buy_count": "1",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Fish",
        "sale_count": ["1"],
        "buy_count": "16",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": ["Coin"],
        "buy": "Wheat",
        "sale_count": ["1"],
        "buy_count": "64",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Oak_Log",
        "sale_count": ["5"],
        "buy_count": "64",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Spruce_Log",
        "sale_count": ["5"],
        "buy_count": "64",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Birch_Log",
        "sale_count": ["3"],
        "buy_count": "64",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Jungle_Log",
        "sale_count": ["3"],
        "buy_count": "64",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Acacia_Log",
        "sale_count": ["3"],
        "buy_count": "64",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Dark_Oak_Log",
        "sale_count": ["3"],
        "buy_count": "64",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": ["Coin"],
        "buy": "Feather",
        "sale_count": ["6"],
        "buy_count": "16",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": ["Coin"],
        "buy": "Egg",
        "sale_count": ["3"],
        "buy_count": "16",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": ["Money"],
        "buy": "White_wool",
        "sale_count": ["3"],
        "buy_count": "16",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Honey_bottle",
        "sale_count": ["3"],
        "buy_count": "16",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": ["Coin"],
        "buy": "Item_frame",
        "sale_count": ["1"],
        "buy_count": "8",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Armor",
        "sale_count": ["20"],
        "buy_count": "1",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": [
            "Money",
            "Coin"
        ],
        "buy": "Helmet",
        "sale_count": [
            "5",
            "2"
        ],
        "buy_count": "1",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": [
            "Money",
            "Coin"
        ],
        "buy": "Chest",
        "sale_count": [
            "8",
            "2"
        ],
        "buy_count": "1",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": [
            "Money",
            "Coin"
        ],
        "buy": "Leggings",
        "sale_count": [
            "7",
            "2"
        ],
        "buy_count": "1",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": [
            "Money",
            "Coin"
        ],
        "buy": "Boots",
        "sale_count": [
            "4",
            "2"
        ],
        "buy_count": "1",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": [
            "Money",
            "Coin"
        ],
        "buy": "Saddle",
        "sale_count": [
            "6",
            "6"
        ],
        "buy_count": "1",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": ["Coin"],
        "buy": "String",
        "sale_count": ["5"],
        "buy_count": "16",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": ["Coin"],
        "buy": "Book",
        "sale_count": ["9"],
        "buy_count": "3",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": [
            "Money",
            "Coin"
        ],
        "buy": "Bookshelves",
        "sale_count": [
            "1",
            "2"
        ],
        "buy_count": "3",
    },
    {
        "type": "farmer",
        "class": "shop",
        "sale": ["Coin"],
        "buy": "Book_and_quill",
        "sale_count": ["5"],
        "buy_count": "3",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Coin"],
        "buy": "Gravel",
        "sale_count": ["4"],
        "buy_count": "64",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Cobblestone",
        "sale_count": ["1"],
        "buy_count": "64x6",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Granite",
        "sale_count": ["1"],
        "buy_count": "64x4",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Diorite",
        "sale_count": ["1"],
        "buy_count": "64x4",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Andesite",
        "sale_count": ["1"],
        "buy_count": "64x4",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Coal",
        "sale_count": ["1"],
        "buy_count": "16",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Nugget_Iron",
        "sale_count": ["3"],
        "buy_count": "64",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": [
            "Money",
            "Coin"
        ],
        "buy": "Lapisdust",
        "sale_count": [
            "1",
            "3"
        ],
        "buy_count": "16",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Coin"],
        "buy": "Quartz",
        "sale_count": ["4"],
        "buy_count": "16",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Nugget_Gold",
        "sale_count": ["2"],
        "buy_count": "32",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Diamond",
        "sale_count": ["3"],
        "buy_count": "32",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Ingot",
        "sale_count": ["2"],
        "buy_count": "1",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Elf_pickaxe_tieri",
        "sale_count": ["10"],
        "buy_count": "1",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Elf_axe_tieri",
        "sale_count": ["10"],
        "buy_count": "1",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Elf_shovel_tieri",
        "sale_count": ["4"],
        "buy_count": "1",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Iron_hummer",
        "sale_count": ["5"],
        "buy_count": "1",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Elf_hummer",
        "sale_count": ["15"],
        "buy_count": "1",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Money"],
        "buy": "People_pickaxe_tieri",
        "sale_count": ["16"],
        "buy_count": "1",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Money"],
        "buy": "People_axe_tieri",
        "sale_count": ["16"],
        "buy_count": "1",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Coin"],
        "buy": "BowTear1",
        "sale_count": ["2"],
        "buy_count": "1",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Money"],
        "buy": "BowTear2",
        "sale_count": ["5"],
        "buy_count": "1",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": [
            "Money",
            "Coin"
        ],
        "buy": "Dagger",
        "sale_count": [
            "1",
            "4"
        ],
        "buy_count": "1",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Blade",
        "sale_count": ["9"],
        "buy_count": "1",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Spear",
        "sale_count": ["3"],
        "buy_count": "1",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Shild",
        "sale_count": ["1"],
        "buy_count": "1",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Money","Coin"],
        "buy": "Arrow",
        "sale_count": ["1","4"],
        "buy_count": "64",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Money","Coin"],
        "buy": "Crystal",
        "sale_count": ["2","4"],
        "buy_count": "5",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Money",],
        "buy": "Armor_tierII",
        "sale_count": ["40"],
        "buy_count": "1",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": [
            "Money",
            "Coin"
        ],
        "buy": "HelmetTierII",
        "sale_count": [
            "10",
            "4"
        ],
        "buy_count": "1",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Money"],
        "buy": "ChestTierII",
        "sale_count": ["17"],
        "buy_count": "1",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": [
            "Money",
            "Coin"
        ],
        "buy": "LeggingsTierII",
        "sale_count": [
            "14",
            "7"
        ],
        "buy_count": "1",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": [
            "Money",
            "Coin"
        ],
        "buy": "BootsTierII",
        "sale_count": [
            "10",
            "4"
        ],
        "buy_count": "1",
    },
    {
        "type": "miner",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Horse_Armor",
        "sale_count": ["14"],
        "buy_count": "1",
    },
    {
        "type": "military",
        "class": "shop",
        "sale": ["Flint"],
        "buy": "Money",
        "sale_count": ["64"],
        "buy_count": "1",
    },
    {
        "type": "military",
        "class": "shop",
        "sale": ["Spider_Eye"],
        "buy": "Money",
        "sale_count": ["24"],
        "buy_count": "5",
    },
    {
        "type": "military",
        "class": "shop",
        "sale": ["Salt"],
        "buy": "Money",
        "sale_count": ["64"],
        "buy_count": "3",
    },
    {
        "type": "military",
        "class": "shop",
        "sale": ["Sugar_Cane"],
        "buy": "Coin",
        "sale_count": ["128"],
        "buy_count": "1",
    },
    {
        "type": "military",
        "class": "shop",
        "sale": ["Bone_meal"],
        "buy": "Coin",
        "sale_count": ["64"],
        "buy_count": "1",
    },
    {
        "type": "military",
        "class": "shop",
        "sale": ["Raw_salmon"],
        "buy": "Coin",
        "sale_count": ["64"],
        "buy_count": "4",
    },
    {
        "type": "military",
        "class": "shop",
        "sale": ["Raw_cod"],
        "buy": "Coin",
        "sale_count": ["64"],
        "buy_count": "4",
    },
    {
        "type": "other",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Horse",
        "sale_count": ["75"],
        "buy_count": "1",
    },
    {
        "type": "other",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Stable",
        "sale_count": ["50"],
        "buy_count": "1",
    },
    {
        "type": "other",
        "class": "shop",
        "sale": ["Money"],
        "buy": "Area",
        "sale_count": ["20"],
        "buy_count": "1",
    },
    {
        "type": "other",
        "class": "shop",
        "sale": ["Money"],
        "buy": "House_Small",
        "sale_count": ["90"],
        "buy_count": "1",
    },
    {
        "type": "other",
        "class": "shop",
        "sale": ["Money"],
        "buy": "HouseT",
        "sale_count": ["110"],
        "buy_count": "1",
    },
    {
        "type": "other",
        "class": "shop",
        "sale": ["Money"],
        "buy": "HouseP",
        "sale_count": ["100"],
        "buy_count": "1",
    }
]